import { Link } from 'react-router-dom';

const email = 'peanutsupport@gmail.com';
const privacy = [
  ['Data controller and contact', `Peanut is operated by Elpida Dimitriadou. For support or questions concerning personal data, contact ${email}.`],
  ['Data we process', 'Account information (name, email address and password hash), optional profile information (role and biography), files and images, text extracted from files for search, notes, tasks, categories, tags, folders and links that you add. The service also processes technical session data, such as IP address, browser information, identifiers and timestamps, for authentication and security. Do not upload highly sensitive data or third-party data unless you have an appropriate lawful basis.'],
  ['Using Peanut without an account', 'In the current version, guest files, notes, tasks and profile information are stored in IndexedDB in that specific browser, without sending their content to the database or R2. Loading the website and checking authentication status still communicate with the hosting infrastructure. Clearing browser data removes the local workspace, and local storage does not sync between devices. Keep copies of important files. Older cloud guest workspaces remain available for optional copying into the browser; this action reads the old data from Cloudflare and does not delete the original copies. Contact us to request deletion of an old cloud workspace before losing its identifier.'],
  ['Purposes and legal bases', 'We use the information necessary to provide your personal workspace, storage, search, authentication and password recovery in order to perform the service you request. Abuse prevention and technical security rely on the legitimate interest of protecting the service and its users. Support requests are used to respond to you and, where required, to comply with legal obligations. We do not use your files for advertising targeting.'],
  ['Service providers and access', 'Cloudflare provides hosting, backend execution, the D1 database and R2 file storage. Brevo receives the recipient email address and the contents of password-reset emails, including the secure reset link. If you email support, the correspondence is processed through Gmail/Google. Workspace content is not shared between accounts. Service administrators and providers may process data when necessary for operation, security or support; the service does not claim to provide end-to-end encryption.'],
  ['Location and international transfers', 'Our providers operate international infrastructure. We do not promise that data will be stored exclusively in Greece or the European Union. Before final public release, the applicable data-processing agreements, actual processing locations and safeguards for transfers outside the EEA must be confirmed. You may request related information using the contact email address.'],
  ['Cookies and local storage', 'We use authentication cookies and local browser storage for the guest workspace, display theme, Pini position and application-update coordination. No advertising tracker or third-party analytics tool is integrated in the reviewed code.'],
  ['Retention and deletion', 'Workspace information remains until you delete it or delete your account. Account deletion removes the associated information from the active database and cloud files. Sessions last for up to 30 days, and password-reset links for up to one hour. Expiration of a token does not necessarily mean immediate physical deletion of its record. Exact retention periods for technical logs, correspondence, backups and abandoned guest workspaces still need to be finalized. We do not promise immediate deletion from every provider backup.'],
  ['Your rights', `Subject to the requirements of the GDPR, you may request access, correction, deletion, restriction or portability, or object to processing based on legitimate interests. Send requests to ${email}. Proportionate verification of identity or ownership of a guest workspace may be required. We generally respond within one month, subject to lawful exceptions. You may lodge a complaint with the Hellenic Data Protection Authority (dpa.gr). We do not use automated decision-making that produces legal or similarly significant effects.`],
];

const terms = [
  ['The service', `Peanut is provided by Elpida Dimitriadou as an application for organizing personal files, notes and tasks. Contact: ${email}. This version is an MVP under development, and its features may change.`],
  ['Accounts and guest workspaces', 'Registration is optional. You are responsible for protecting your password and device. A new guest workspace stores its content only in that specific browser through IndexedDB. Loading the service requires an internet connection, and we do not guarantee complete offline operation. Clearing browser data or using another browser will not preserve the local workspace. Creating an account does not automatically transfer guest data into that account.'],
  ['Your content', 'You retain the rights to your content. You grant us only the permission required to store, process and display it in order to provide the service, including extracting text for search. Only upload content that you have the right to use and store.'],
  ['Acceptable use', 'Illegal content, malicious files, infringement of third-party rights, attempts to access other workspaces and abuse of the infrastructure are prohibited. We may restrict access when necessary for security or legal compliance, notifying you where practical and lawful.'],
  ['Uploads and limits', 'You may import up to 10 files at a time. The current limit is 50 MB per document and 20 MB per image, with checks for supported file types and file contents. Acceptance of a file is not a guarantee that it is safe. Limits may change with notice.'],
  ['Availability and backups', 'Interruptions, errors or loss of access may occur. Keep your own copies of important files. Peanut is not a guaranteed archival service, a password manager or an appropriate sole storage location for critical data. These terms do not limit mandatory consumer rights or liability that cannot lawfully be excluded.'],
  ['Deletion, charges and changes', 'You can delete your account from your profile or request assistance by email. The current version does not include payments or subscriptions. Any future charge will be announced before it applies and will not be activated automatically without the required agreement. Material changes to these terms or to data processing will be communicated before they take effect where required.'],
];

export function LegalPage({ kind }: { kind: 'privacy' | 'terms' }) {
  return <main className="min-h-dvh bg-[#fffaf3] px-4 py-10 text-violet-950 dark:bg-[#171329] dark:text-violet-100">
    <article className="mx-auto max-w-3xl rounded-3xl border border-violet-200 bg-white p-6 shadow-sm dark:border-violet-800 dark:bg-[#211b35] sm:p-10">
      <Link to="/" className="text-sm text-violet-600 dark:text-violet-300">← Back to Peanut</Link>
      <h1 className="mt-6 font-serif text-3xl font-bold">{kind === 'privacy' ? 'Privacy Policy' : 'Terms of Use'}</h1>
      <p className="mt-2 text-sm text-violet-500">Last updated: September 13, 2026</p>
      <p className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-900 dark:bg-amber-950/40 dark:text-amber-200">Draft for review before final public release. The operational and legal details identified below still need to be finalized.</p>
      {(kind === 'privacy' ? privacy : terms).map(([title, body]) => <section key={title} className="mt-7"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 whitespace-pre-line text-sm leading-7">{body}</p></section>)}
      <nav aria-label="Legal information" className="mt-9 flex flex-wrap gap-5 border-t border-violet-100 pt-5 text-sm text-violet-600 dark:border-violet-800 dark:text-violet-300"><Link to="/privacy">Privacy Policy</Link><Link to="/terms">Terms of Use</Link><a href={`mailto:${email}`}>Support</a></nav>
    </article>
  </main>;
}
