import { importDocumentFieldsSchema, type DocumentRecord, type Tag } from '@peanut/contracts';
import { ensureCategory, ensureTags, WorkspaceError } from './workspace';
import { validateUploadedFile } from './uploadValidation';

interface Row { id:string;title:string;categoryId:string|null;categoryName:string|null;categoryColor:string|null;createdAt:string;updatedAt:string;versionId:string;versionLabel:string;originalFilename:string;storageKey:string;mimeType:string;fileSize:number;importedAt:string;extractedText:string;contentHash:string|null }
interface TagRow { documentId:string;id:string;name:string }
const select=`SELECT d.id,d.title,d.category_id AS categoryId,c.name AS categoryName,c.color AS categoryColor,d.created_at AS createdAt,d.updated_at AS updatedAt,v.id AS versionId,v.version_label AS versionLabel,v.original_filename AS originalFilename,v.storage_key AS storageKey,v.mime_type AS mimeType,v.file_size AS fileSize,v.imported_at AS importedAt,v.extracted_text AS extractedText,v.content_hash AS contentHash FROM documents d JOIN document_versions v ON v.document_id=d.id AND v.owner_id=d.owner_id AND v.is_current=1 LEFT JOIN categories c ON c.id=d.category_id AND c.owner_id=d.owner_id WHERE d.owner_id=?`;
const supported:Record<string,string>={pdf:'application/pdf',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',txt:'text/plain',md:'text/markdown',markdown:'text/markdown',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',gif:'image/gif',avif:'image/avif'};
const noTextMarker='[PINIT_NO_TEXT]';

async function hydrate(db:D1Database,owner:string,rows:Row[]):Promise<DocumentRecord[]>{if(!rows.length)return[];const found=await db.prepare('SELECT dt.document_id AS documentId,t.id,t.name FROM document_tags dt JOIN tags t ON t.id=dt.tag_id AND t.owner_id=dt.owner_id WHERE dt.owner_id=? ORDER BY t.name COLLATE NOCASE').bind(owner).all<TagRow>();const grouped=new Map<string,Tag[]>();for(const tag of found.results){const values=grouped.get(tag.documentId)??[];values.push({id:tag.id,name:tag.name});grouped.set(tag.documentId,values);}return rows.map(row=>({id:row.id,title:row.title,category:row.categoryId&&row.categoryName&&row.categoryColor?{id:row.categoryId,name:row.categoryName,color:row.categoryColor}:null,tags:grouped.get(row.id)??[],currentVersion:{id:row.versionId,label:row.versionLabel,originalFilename:row.originalFilename,mimeType:row.mimeType,fileSize:row.fileSize,importedAt:row.importedAt},createdAt:row.createdAt,updatedAt:row.updatedAt}));}
async function requireRow(db:D1Database,owner:string,id:string){const value=await db.prepare(`${select} AND d.id=?`).bind(owner,id).first<Row>();if(!value)throw new WorkspaceError(404,'Document not found.','DOCUMENT_NOT_FOUND');return value;}
export async function listDocuments(db:D1Database,owner:string){const result=await db.prepare(`${select} ORDER BY d.updated_at DESC`).bind(owner).all<Row>();return hydrate(db,owner,result.results);}
export async function getDocument(db:D1Database,owner:string,id:string){const value=await requireRow(db,owner,id);return{document:(await hydrate(db,owner,[value]))[0]!,extractedText:value.extractedText===noTextMarker?'':value.extractedText};}
export async function listPendingTextDocuments(db:D1Database,owner:string){const result=await db.prepare(`${select} AND v.extracted_text='' AND v.mime_type IN ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document') ORDER BY d.updated_at DESC`).bind(owner).all<Row>();return result.results.map(row=>({id:row.id,originalFilename:row.originalFilename}));}
export async function updateExtractedText(db:D1Database,owner:string,id:string,body:unknown){const value=await requireRow(db,owner,id);if(!body||typeof body!=='object'||typeof (body as {extractedText?:unknown}).extractedText!=='string')throw new WorkspaceError(400,'Extracted text is required.','EXTRACTED_TEXT_REQUIRED');const text=(body as {extractedText:string}).extractedText.slice(0,4_000_000)||noTextMarker;await db.prepare('UPDATE document_versions SET extracted_text=? WHERE owner_id=? AND id=?').bind(text,owner,value.versionId).run();}
function parseTags(value:FormDataEntryValue|null):string[]{const raw=String(value??'').trim();if(!raw)return[];if(raw.startsWith('[')){const parsed:unknown=JSON.parse(raw);if(Array.isArray(parsed)&&parsed.every(item=>typeof item==='string'))return parsed;throw new WorkspaceError(400,'Tags must be a list of strings.','INVALID_TAGS');}return raw.split(',').map(tag=>tag.trim()).filter(Boolean);}
async function hash(file:File){const digest=await crypto.subtle.digest('SHA-256',await file.arrayBuffer());return[...new Uint8Array(digest)].map(value=>value.toString(16).padStart(2,'0')).join('');}
export async function importDocument(db:D1Database,files:R2Bucket,owner:string,form:FormData){const value=form.get('file');if(!(value instanceof File))throw new WorkspaceError(400,'Choose a document to import.','FILE_REQUIRED');const extension=value.name.split('.').pop()?.toLowerCase()??'',mimeType=supported[extension];if(!mimeType)throw new WorkspaceError(400,'Unsupported file type. Peanut accepts PDF, DOCX, TXT, Markdown, JPG, PNG, WebP, GIF and AVIF.','UNSUPPORTED_FILE_TYPE');await validateUploadedFile(value,extension);const contentHash=await hash(value),duplicate=await db.prepare('SELECT d.title FROM document_versions v JOIN documents d ON d.id=v.document_id AND d.owner_id=v.owner_id WHERE v.owner_id=? AND v.content_hash=? LIMIT 1').bind(owner,contentHash).first<{title:string}>();if(duplicate)throw new WorkspaceError(409,`This file is already saved as “${duplicate.title}”.`,'DUPLICATE_DOCUMENT');const title=String(form.get('title')??'').trim()||value.name.replace(/\.[^.]+$/u,''),fields=importDocumentFieldsSchema.parse({title,category:String(form.get('category')??'').trim()||null,tags:parseTags(form.get('tags')),version:String(form.get('version')??'').trim()||'1.0'}),documentId=crypto.randomUUID(),versionId=crypto.randomUUID(),now=new Date().toISOString(),key=`users/${owner}/documents/${documentId}/${versionId}.${extension}`,clientText=String(form.get('extractedText')??'').slice(0,4_000_000),extractedText=clientText||(['txt','md','markdown'].includes(extension)?await value.text():'');const categoryId=await ensureCategory(db,owner,fields.category),tagIds=await ensureTags(db,owner,fields.tags);await files.put(key,value.stream(),{httpMetadata:{contentType:mimeType},customMetadata:{ownerId:owner,originalFilename:value.name}});try{await db.batch([db.prepare('INSERT INTO documents (id,owner_id,title,category_id,created_at,updated_at) VALUES (?,?,?,?,?,?)').bind(documentId,owner,fields.title,categoryId,now,now),db.prepare('INSERT INTO document_versions (id,owner_id,document_id,version_label,original_filename,storage_key,mime_type,file_size,content_hash,extracted_text,imported_at,is_current) VALUES (?,?,?,?,?,?,?,?,?,?,?,1)').bind(versionId,owner,documentId,fields.version,value.name,key,mimeType,value.size,contentHash,extractedText,now),...tagIds.map(tagId=>db.prepare('INSERT INTO document_tags (owner_id,document_id,tag_id) VALUES (?,?,?)').bind(owner,documentId,tagId))]);}catch(error){await files.delete(key);throw error;}return(await hydrate(db,owner,[await requireRow(db,owner,documentId)]))[0]!;}
export async function getFile(db:D1Database,files:R2Bucket,owner:string,id:string){const value=await requireRow(db,owner,id),object=await files.get(value.storageKey);if(!object)throw new WorkspaceError(404,'Document file not found.','DOCUMENT_FILE_NOT_FOUND');return new Response(object.body,{headers:{'Content-Type':value.mimeType,'Content-Disposition':`inline; filename*=UTF-8''${encodeURIComponent(value.originalFilename)}`,'Cache-Control':'private, no-store'}});}
export async function deleteDocument(db:D1Database,files:R2Bucket,owner:string,id:string){const value=await requireRow(db,owner,id);await db.prepare('DELETE FROM documents WHERE owner_id=? AND id=?').bind(owner,id).run();await files.delete(value.storageKey);}
