import {
  createIntegrationEntrySchema, createIntegrationFolderSchema, createIntegrationSpaceSchema,
  updateIntegrationEntrySchema, updateIntegrationFolderSchema, updateIntegrationSpaceSchema,
  type IntegrationEntry, type IntegrationFolder, type IntegrationSpace,
} from '@peanut/contracts';
import { WorkspaceError } from './workspace';

interface EntryRow { id: string; folderId: string; title: string; description: string; url: string | null; originalFilename: string | null; storageKey: string | null; mimeType: string | null; fileSize: number | null; createdAt: string; updatedAt: string }
const entrySelect = 'SELECT id, folder_id AS folderId, title, description, url, original_filename AS originalFilename, storage_key AS storageKey, mime_type AS mimeType, file_size AS fileSize, created_at AS createdAt, updated_at AS updatedAt FROM integration_entries WHERE owner_id = ?';
const hydrate = (row: EntryRow): IntegrationEntry => ({ id: row.id, folderId: row.folderId, title: row.title, description: row.description, url: row.url, attachment: row.originalFilename && row.mimeType && row.fileSize !== null ? { originalFilename: row.originalFilename, mimeType: row.mimeType, fileSize: row.fileSize } : null, createdAt: row.createdAt, updatedAt: row.updatedAt });

export async function listIntegrationWorkspace(db: D1Database, owner: string) {
  const [spaces, folders, entries] = await Promise.all([
    db.prepare('SELECT id, name, created_at AS createdAt, updated_at AS updatedAt FROM integration_spaces WHERE owner_id = ? ORDER BY created_at').bind(owner).all<IntegrationSpace>(),
    db.prepare('SELECT id, space_id AS spaceId, name, parent_id AS parentId, created_at AS createdAt, updated_at AS updatedAt FROM integration_folders WHERE owner_id = ? ORDER BY name COLLATE NOCASE').bind(owner).all<IntegrationFolder>(),
    db.prepare(`${entrySelect} ORDER BY updated_at DESC`).bind(owner).all<EntryRow>(),
  ]);
  return { spaces: spaces.results, folders: folders.results, entries: entries.results.map(hydrate) };
}

async function space(db: D1Database, owner: string, id: string) { const row = await db.prepare('SELECT id, name, created_at AS createdAt, updated_at AS updatedAt FROM integration_spaces WHERE owner_id=? AND id=?').bind(owner, id).first<IntegrationSpace>(); if (!row) throw new WorkspaceError(404, 'Workspace section not found.', 'INTEGRATION_SPACE_NOT_FOUND'); return row; }
async function folder(db: D1Database, owner: string, id: string) { const row = await db.prepare('SELECT id, space_id AS spaceId, name, parent_id AS parentId, created_at AS createdAt, updated_at AS updatedAt FROM integration_folders WHERE owner_id=? AND id=?').bind(owner, id).first<IntegrationFolder>(); if (!row) throw new WorkspaceError(404, 'Integration folder not found.', 'INTEGRATION_FOLDER_NOT_FOUND'); return row; }
async function entry(db: D1Database, owner: string, id: string) { const row = await db.prepare(`${entrySelect} AND id=?`).bind(owner, id).first<EntryRow>(); if (!row) throw new WorkspaceError(404, 'Integration item not found.', 'INTEGRATION_ENTRY_NOT_FOUND'); return row; }

export async function createSpace(db: D1Database, owner: string, body: unknown) { const input=createIntegrationSpaceSchema.parse(body), id=crypto.randomUUID(), now=new Date().toISOString(); try { await db.prepare('INSERT INTO integration_spaces (id,owner_id,name,created_at,updated_at) VALUES (?,?,?,?,?)').bind(id,owner,input.name,now,now).run(); } catch { throw new WorkspaceError(409,'A section with this name already exists.','INTEGRATION_SPACE_EXISTS'); } return {id,name:input.name,createdAt:now,updatedAt:now}; }
export async function updateSpace(db:D1Database,owner:string,id:string,body:unknown){const input=updateIntegrationSpaceSchema.parse(body),current=await space(db,owner,id),now=new Date().toISOString();await db.prepare('UPDATE integration_spaces SET name=?,updated_at=? WHERE owner_id=? AND id=?').bind(input.name??current.name,now,owner,id).run();return{...current,name:input.name??current.name,updatedAt:now};}
export async function deleteSpace(db:D1Database,files:R2Bucket,owner:string,id:string){await space(db,owner,id);const keys=await db.prepare('SELECT e.storage_key AS storageKey FROM integration_entries e JOIN integration_folders f ON f.id=e.folder_id AND f.owner_id=e.owner_id WHERE e.owner_id=? AND f.space_id=? AND e.storage_key IS NOT NULL').bind(owner,id).all<{storageKey:string}>();await db.prepare('DELETE FROM integration_spaces WHERE owner_id=? AND id=?').bind(owner,id).run();await Promise.all(keys.results.map(row=>files.delete(row.storageKey)));}

export async function createFolder(db:D1Database,owner:string,body:unknown){const input=createIntegrationFolderSchema.parse(body);await space(db,owner,input.spaceId);if(input.parentId){const parent=await folder(db,owner,input.parentId);if(parent.spaceId!==input.spaceId)throw new WorkspaceError(400,'A folder must stay inside its section.','INVALID_FOLDER_SPACE');}const id=crypto.randomUUID(),now=new Date().toISOString();await db.prepare('INSERT INTO integration_folders (id,owner_id,space_id,parent_id,name,created_at,updated_at) VALUES (?,?,?,?,?,?,?)').bind(id,owner,input.spaceId,input.parentId,input.name,now,now).run();return{id,spaceId:input.spaceId,parentId:input.parentId,name:input.name,createdAt:now,updatedAt:now};}
export async function updateFolder(db:D1Database,owner:string,id:string,body:unknown){const input=updateIntegrationFolderSchema.parse(body),current=await folder(db,owner,id),parentId=input.parentId===undefined?current.parentId:input.parentId;if(parentId===id)throw new WorkspaceError(400,'A folder cannot contain itself.','INVALID_FOLDER_PARENT');if(parentId){const parent=await folder(db,owner,parentId);if(parent.spaceId!==current.spaceId)throw new WorkspaceError(400,'A folder must stay inside its section.','INVALID_FOLDER_SPACE');}const now=new Date().toISOString();await db.prepare('UPDATE integration_folders SET name=?,parent_id=?,updated_at=? WHERE owner_id=? AND id=?').bind(input.name??current.name,parentId,now,owner,id).run();return{...current,name:input.name??current.name,parentId,updatedAt:now};}
export async function deleteFolder(db:D1Database,files:R2Bucket,owner:string,id:string){await folder(db,owner,id);const keys=await db.prepare('WITH RECURSIVE tree(id) AS (SELECT id FROM integration_folders WHERE owner_id=? AND id=? UNION ALL SELECT f.id FROM integration_folders f JOIN tree t ON f.parent_id=t.id WHERE f.owner_id=?) SELECT e.storage_key AS storageKey FROM integration_entries e WHERE e.owner_id=? AND e.folder_id IN (SELECT id FROM tree) AND e.storage_key IS NOT NULL').bind(owner,id,owner,owner).all<{storageKey:string}>();await db.prepare('DELETE FROM integration_folders WHERE owner_id=? AND id=?').bind(owner,id).run();await Promise.all(keys.results.map(row=>files.delete(row.storageKey)));}

export async function createEntry(db:D1Database,owner:string,body:unknown){const input=createIntegrationEntrySchema.parse(body);await folder(db,owner,input.folderId);const id=crypto.randomUUID(),now=new Date().toISOString();await db.prepare('INSERT INTO integration_entries (id,owner_id,folder_id,title,description,url,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?)').bind(id,owner,input.folderId,input.title,input.description,input.url,now,now).run();return hydrate({id,folderId:input.folderId,title:input.title,description:input.description,url:input.url,originalFilename:null,storageKey:null,mimeType:null,fileSize:null,createdAt:now,updatedAt:now});}
export async function updateEntry(db:D1Database,owner:string,id:string,body:unknown){const input=updateIntegrationEntrySchema.parse(body),current=await entry(db,owner,id),folderId=input.folderId??current.folderId;await folder(db,owner,folderId);await db.prepare('UPDATE integration_entries SET folder_id=?,title=?,description=?,url=?,updated_at=? WHERE owner_id=? AND id=?').bind(folderId,input.title??current.title,input.description??current.description,input.url===undefined?current.url:input.url,new Date().toISOString(),owner,id).run();return hydrate(await entry(db,owner,id));}
export async function createPdf(db:D1Database,files:R2Bucket,owner:string,form:FormData){const value=form.get('file');if(!(value instanceof File)||value.type!=='application/pdf')throw new WorkspaceError(400,'Choose a PDF file.','FILE_REQUIRED');if(value.size>50*1024*1024)throw new WorkspaceError(413,'PDF files can be up to 50 MB.','FILE_TOO_LARGE');const folderId=String(form.get('folderId')??'');await folder(db,owner,folderId);const id=crypto.randomUUID(),now=new Date().toISOString(),key=`users/${owner}/integrations/${id}.pdf`,title=String(form.get('title')??'').trim()||value.name.replace(/\.pdf$/iu,''),description=String(form.get('description')??'').trim().slice(0,20000);await files.put(key,value.stream(),{httpMetadata:{contentType:'application/pdf'},customMetadata:{ownerId:owner,originalFilename:value.name}});try{await db.prepare('INSERT INTO integration_entries (id,owner_id,folder_id,title,description,url,original_filename,storage_key,mime_type,file_size,created_at,updated_at) VALUES (?,?,?,?,?,NULL,?,?,?,?,?,?)').bind(id,owner,folderId,title,description,value.name,key,value.type,value.size,now,now).run();}catch(error){await files.delete(key);throw error;}return hydrate(await entry(db,owner,id));}
export async function getPdf(db:D1Database,files:R2Bucket,owner:string,id:string){const current=await entry(db,owner,id);if(!current.storageKey||!current.originalFilename)throw new WorkspaceError(404,'PDF not found.','PDF_NOT_FOUND');const object=await files.get(current.storageKey);if(!object)throw new WorkspaceError(404,'PDF not found.','PDF_NOT_FOUND');return new Response(object.body,{headers:{'Content-Type':current.mimeType??'application/pdf','Content-Disposition':`inline; filename*=UTF-8''${encodeURIComponent(current.originalFilename)}`,'Cache-Control':'private, no-store'}});}
export async function deleteEntry(db:D1Database,files:R2Bucket,owner:string,id:string){const current=await entry(db,owner,id);await db.prepare('DELETE FROM integration_entries WHERE owner_id=? AND id=?').bind(owner,id).run();if(current.storageKey)await files.delete(current.storageKey);}
