import type { ExtractiveAnswerResponse, SearchResult } from '@peanut/contracts';

interface SearchRow { entityType:'document'|'note'|'integration'|'category'; entityId:string; title:string; content:string; category:string|null; tags:string|null; version:string|null; mimeType:string|null; integrationFolderId:string|null; updatedAt:string }
const normalize=(value:string)=>value.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase();
function excerpt(content:string,needle:string){const clean=content.replace(/\s+/gu,' ').trim();if(!clean)return'';const at=normalize(clean).indexOf(needle);const start=Math.max(0,at<0?0:at-90),end=Math.min(clean.length,start+260);return`${start?'…':''}${clean.slice(start,end)}${end<clean.length?'…':''}`;}

async function rows(db:D1Database,owner:string):Promise<SearchRow[]>{const result=await db.prepare(`
  SELECT 'document' AS entityType,d.id AS entityId,d.title,(d.title||' '||v.original_filename||' '||v.extracted_text) AS content,c.name AS category,GROUP_CONCAT(t.name,' ') AS tags,v.version_label AS version,v.mime_type AS mimeType,NULL AS integrationFolderId,d.updated_at AS updatedAt
  FROM documents d JOIN document_versions v ON v.document_id=d.id AND v.owner_id=d.owner_id AND v.is_current=1 LEFT JOIN categories c ON c.id=d.category_id AND c.owner_id=d.owner_id LEFT JOIN document_tags dt ON dt.document_id=d.id AND dt.owner_id=d.owner_id LEFT JOIN tags t ON t.id=dt.tag_id AND t.owner_id=dt.owner_id WHERE d.owner_id=? GROUP BY d.id
  UNION ALL SELECT 'note',n.id,n.title,(n.title||' '||n.content),c.name,GROUP_CONCAT(t.name,' '),NULL,NULL,NULL,n.updated_at FROM notes n LEFT JOIN categories c ON c.id=n.category_id AND c.owner_id=n.owner_id LEFT JOIN note_tags nt ON nt.note_id=n.id AND nt.owner_id=n.owner_id LEFT JOIN tags t ON t.id=nt.tag_id AND t.owner_id=nt.owner_id WHERE n.owner_id=? GROUP BY n.id
  UNION ALL SELECT 'integration',e.id,e.title,(e.title||' '||e.description||' '||COALESCE(e.original_filename,'')||' '||f.name||' '||s.name),NULL,NULL,NULL,e.mime_type,e.folder_id,e.updated_at FROM integration_entries e JOIN integration_folders f ON f.id=e.folder_id AND f.owner_id=e.owner_id JOIN integration_spaces s ON s.id=f.space_id AND s.owner_id=f.owner_id WHERE e.owner_id=?
  UNION ALL SELECT 'category',c.id,c.name,c.name,c.name,NULL,NULL,NULL,NULL,c.updated_at FROM categories c WHERE c.owner_id=?
`).bind(owner,owner,owner,owner).all<SearchRow>();return result.results;}

export async function searchWorkspace(db:D1Database,owner:string,query:string){const needle=normalize(query.trim());if(!needle)return{query,results:[]};const results:SearchResult[]=(await rows(db,owner)).flatMap(row=>{const haystack=normalize([row.title,row.content,row.category,row.tags].filter(Boolean).join(' '));if(!haystack.includes(needle))return[];const titleHit=normalize(row.title).includes(needle);return[{entityType:row.entityType,entityId:row.entityId,title:row.title,snippet:excerpt(row.content,needle),rank:titleHit?2:1,category:row.category,tags:row.tags?.split(' ').filter(Boolean)??[],version:row.version,mimeType:row.mimeType,integrationFolderId:row.integrationFolderId,updatedAt:row.updatedAt}];}).sort((a,b)=>b.rank-a.rank||b.updatedAt.localeCompare(a.updatedAt)).slice(0,50);return{query,results};}
export async function answerWorkspace(db:D1Database,owner:string,question:string):Promise<ExtractiveAnswerResponse>{const {results}=await searchWorkspace(db,owner,question);const sources=results.filter(result=>result.entityType!=='category').slice(0,5).map(result=>({entityType:result.entityType as 'document'|'note'|'integration',entityId:result.entityId,title:result.title,excerpt:result.snippet,category:result.category,mimeType:result.mimeType,integrationFolderId:result.integrationFolderId}));return{question,answer:sources[0]?.excerpt||null,sources};}
